name: RussianRoulette
main: main.java.com.texasgamer.russianroulette.RussianRoulette
version: 1.2-SNAPSHOT
commands:
    rr:
        description: Press your luck
        usage: /rr
    moab:
        description: Drop the mother of all bombs
        usage: /moab
    nuke:
        description: Drop a nuke
        usage: /nuke
    roulette:
        description: About the plugin
        usage: /roulette
permissions:
    roulette.*:
        description: Gives access to all commands (NOT roulette.safe!)
        children:
            roulette.rr: true
            roulette.moab: true
            roulette.nuke: true
    roulette.rr:
        description: Allows usage of /rr
        default: false
    roulette.moab:
        description: Allows usage of /moab
        default: false
    roulette.nuke:
        description: Allows usage of /nuke
        default: false
    roulette.safe:
        description: Prevents the player from being kicked
        default: false